name: Manual Trigger Workflow

on:
  workflow_dispatch: # Enables manual trigger

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "This workflow was triggered manually"
